### ISSUE TITLE
Better instructions on how to install

### ISSUE THREAD

**Issue by KodeStar** [kiwionly/elasticsearch-image#13]
as /bin/plugin install kiwionly/elasticsearch-image doesn't work I've installed gradle, but have no idea how to actually get it to install this "Create this plugin using gradle, task gradle plugin, then unzip to %elasticsearch%/plugins folder" is not very easy to follow...

**Comment by kiwionly** [comment]
I had update the readme (for 2.3.4).

for 2.3.3, first install gradle, then set you %gradle_home%/bin to path, so when u open cmd/shell, you had a command >gradle.

then just go to E.S. image directory, and enter "gradle plugin", once done, u can find the distribution under build/distribution, unzip it to you E.S plugins folder. 

so it look like 

%E.S_HOME%/plugins/elastic-image-x.x.x/jar_file_here
