### ISSUE TITLE
Caused by: MapperParsingException[No type specified for field [metadata]]

### ISSUE THREAD

**Issue by stallyen** [kiwionly/elasticsearch-image#15]
Hi:

I have created mapping.json in my java application. With REST, mapping as provided in documentation works fine but not with JAVA API  in elastic search. Following is code:

For Mapping :

public void createlireMapping(elasticsearchcon elasticSearchConnection) {

```
    CreateIndexRequestBuilder createIndexRequestBuilder = elasticSearchConnection.getClient().admin().indices().prepareCreate(indexName);
    Path str = Paths.get(settingsFile);
    try {
        String settings_json = new String(Files.readAllBytes(str));
        createIndexRequestBuilder.setSource(settings_json);
        String mapping_json = new String(Files.readAllBytes(Paths.get(jsonFileName)));
        createIndexRequestBuilder.addMapping(mappingType, mapping_json);
        System.out.println("it do");
        CreateIndexResponse indexResponse = createIndexRequestBuilder.execute().actionGet();


    } catch (IOException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
}
```

Mapping.json:
{
        "properties": {
                "type": "image",
                "feature": {
                    "CEDD": {
                        "hash": ["BIT_SAMPLING"]
                    },
                    "JCD": {
                        "hash": ["BIT_SAMPLING", "LSH"]
                    }
                },
                "metadata": {
                    "jpeg.image_width": {
                        "type": "string",
                        "store": "yes"
                    },
                    "jpeg.image_height": {
                        "type": "string",
                        "store": "yes"
                    }
                }
            }
    }

Error:  Exception in thread "main" MapperParsingException[Failed to parse mapping [imagess]: No type specified for field [metadata]]; nested: MapperParsingException[No type specified for field [metadata]];

Am I doing something wrong in mapping?

**Comment by kiwionly** [comment]
you may print out the mapping json to ensure that the format you send is correct.

hope this help.
