### ISSUE TITLE
install report (Could not find plugin descriptor 'plugin-descriptor.properties')

### ISSUE THREAD

**Issue by gastonwu** [kiwionly/elasticsearch-image#2]
(elasticsearch version:2.2.0)

bin/plugin install kiwionly/elasticsearch-image

Verifying https://github.com/kiwionly/elasticsearch-image/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

how to fix it?
thanks

**Comment by kiwionly** [comment]
hi, 

Are you using gradle for build? just call the task > gradle plugin 

It should generate the plugin artifact. Maven no longer support, it leave they for using in eclipse development only.

**Comment by 97-109-107** [comment]
I figured out how to complete these tasks; here are my notes should anyone be in need:
- Get 2.2.0 from elastic.co
- Get the the master release of `elasticsearch-image`
- Inside `elasticsearch-image` run `gradle plugin`
- Tell ES to install the result of the gradle build (from `elasticsearch-image-master/build/distributions/elasticsearch-image-2.2.0.zip`) (with `./bin/plugin install file:///file/path`)

**Comment by gastonwu** [comment]
follow @97-109-107 step, it works!

thanks!!

**Comment by kiwionly** [comment]
after running > gradle plugin, it will produce an zip file.

you can manually install by unzip the file in the elasticsearch plugin folder.
