### ISSUE TITLE
 "unsupported parameters" error

### ISSUE THREAD

**Issue by emaza** [kiwionly/elasticsearch-image#3]
elastic.version = 2.2.0

I created the plugin via gradle and unzip to %elasticsearch%/plugins folder.
Then trying to create mapping like example in  Redme. I have this "unsupported parameters" error:

-first create index:
curl -XPUT 'localhost:9200/test?pretty'
-second crete mapping
"like example in  README.md"
--return
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Mapping definition for [my_img] has unsupported parameters:  [feature : {CEDD={hash=[BIT_SAMPLING]}, JCD={hash=[BIT_SAMPLING, LSH]}}] [metadata : {jpeg.image_width={type=string}, jpeg.image_height={type=string}}]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Mapping definition for [my_img] has unsupported parameters:  [feature : {CEDD={hash=[BIT_SAMPLING]}, JCD={hash=[BIT_SAMPLING, LSH]}}] [metadata : {jpeg.image_width={type=string}, jpeg.image_height={type=string}}]"
  },
  "status": 400
}

**Comment by kiwionly** [comment]
you need to made sure your index format and url is correct.

it look like is input issue.
