### ISSUE TITLE
unsupported parameters" error

### ISSUE THREAD

**Issue by ghost** [kiwionly/elasticsearch-image#6]
elastic.version = 2.2.0
using branch : https://github.com/kiwionly/elasticsearch-image
I created the plugin via gradle and unzip to %elasticsearch%/plugins folder.
Then trying to create mapping like example in Redme. I have this "unsupported parameters" error:

-first create index:
curl -XPUT 'localhost:9200/test?pretty'
-second crete mapping
"like example in README.md"
--return
{
"error": {
"root_cause": [
{
"type": "mapper_parsing_exception",
"reason": "Mapping definition for [my_img] has unsupported parameters: [feature : {CEDD={hash=[BIT_SAMPLING]}, JCD={hash=[BIT_SAMPLING, LSH]}}] [metadata : {jpeg.image_width={type=string}, jpeg.image_height={type=string}}]"
}
],
"type": "mapper_parsing_exception",
"reason": "Mapping definition for [my_img] has unsupported parameters: [feature : {CEDD={hash=[BIT_SAMPLING]}, JCD={hash=[BIT_SAMPLING, LSH]}}] [metadata : {jpeg.image_width={type=string}, jpeg.image_height={type=string}}]"
},
"status": 400
}

**Comment by ghost** [comment]
longtran@longtran:/$  curl -XPUT 'http://localhost:9200/test/' -d '{
    "settings" : {
        "index" : {
"number_of_shards" : 5,
"number_of_replicas" : 2,
"index.version.created" : 1070499
        }
    }
}'
{"acknowledged":true}longtran@longtran:/$ 
longtran@longtran:/$ 
longtran@longtran:/$ 
longtran@longtran:/$ 
longtran@longtran:/$ curl -XPUT 'localhost:9200/test/test/_mapping' -d '{

> ```
> "test": {
>     "properties": {
>         "my_img": {
>             "type": "image",
>             "feature": {
>                 "CEDD": {
>                     "hash": "BIT_SAMPLING"
>                 },
>                 "JCD": {
>                     "hash": ["BIT_SAMPLING", "LSH"]
>                 }
>             },
>             "metadata": {
>                 "jpeg.image_width": {
>                     "type": "string",
>                     "store": "yes"
>                 },
>                 "jpeg.image_height": {
>                     "type": "string",
>                     "store": "yes"
>                 }
>             }
>         }
>     }
> }
> ```
> 
> }'
> {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"test","index":"test"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"test","index":"test"},"status":404}longtran@longtran:/$

**Comment by ghost** [comment]
@kiwionly , i built and installed the plugin but elastic mapping throws a lot of exceptions when started because of the plugin,was anyone able to successfully use it ?

**Comment by kiwionly** [comment]
hi,

curl -XPUT 'localhost:9200/test/test/_mapping/{your_index_type}

e.g
//as the sample using "test", specify "test" in url.
curl -XPUT 'localhost:9200/test/test/_mapping/test

**Comment by ghost** [comment]
@kiwionly  i stll have not understanded your explaination. Could you explain more clearly? Please instruct me step by step.thanks.

**Comment by kiwionly** [comment]
read here

[https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html)

**Comment by Artgit** [comment]
@kiwionly 

`curl -XPUT 'localhost:9200/test/test/_mapping/test'`

fails with 

`No handler found for uri [/test/test/_mapping/test] and method [PUT]`
